# Generated by Django 3.0.7 on 2020-07-17 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20200717_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookmetadata',
            name='time_read',
        ),
        migrations.AddField(
            model_name='userbookmetadata',
            name='date_read',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField()),
                ('date_start', models.DateField(auto_now_add=True)),
                ('date_end', models.DateField()),
                ('date_complete', models.DateField(blank=True, null=True)),
                ('books', models.ManyToManyField(to='api.UserBookMetadata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
