# Generated by Django 3.0.7 on 2020-07-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200717_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='books',
        ),
        migrations.AddField(
            model_name='goal',
            name='book_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goal',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
