# Generated by Django 3.0.7 on 2020-07-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_goal_count_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(max_length=300000),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='cover',
            field=models.CharField(max_length=300000),
        ),
    ]
