# Generated by Django 3.0.7 on 2020-07-29 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200728_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('average_rating', models.IntegerField(default=0)),
                ('total_ratings', models.IntegerField(default=0)),
                ('read_count', models.IntegerField(default=0)),
                ('collection_count', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Book')),
            ],
        ),
    ]
